# https://docs.flutter.dev/release/breaking-changes/flutter-generate-i10n-source
synthetic-package: false

arb-dir: lib/l10n
template-arb-file: app_en.arb

# run "flutter gen-l10n"  to generate the localization files
# output-localization-file: app_localizations.dart
output-dir: lib/l10n/generated